spring:
  application:
    name: learn-spring
  profiles:
    active: dev

  # 데이터베이스 설정
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/learn-spring}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      pool-name: LearnSpringHikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true

  # Spring Data REST 설정
  data:
    rest:
      base-path: /api/data-rest
      detection-strategy: ANNOTATED  # ANNOTATED로 설정하여 @RepositoryRestResource 어노테이션이 있는 Repository만 REST API로 노출

  # Thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  # 기타 Spring 설정
  docker:
    compose:
      enabled: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  output:
    ansi:
      enabled: never
  security:
    filter:
      jwt.enabled: ${SPRING_SECURITY_FILTER_JWT_ENABLED:false}
    user:
      name: admin
      password: admin

# 서버 설정
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-password: changeit
    key-store-type: PKCS12

# 로깅 설정
logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.boot.actuate: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.sleuth: DEBUG
    org.springframework.boot.autoconfigure.web.servlet.error: DEBUG

# 암호화 설정
jasypt:
  encryptor:
    password: learn-spring-encryption-key-=a2V5X3ZhbHVlX3RoYXRfaXNfYXRfbGVhc3RfMjU2X2JpdHNfbG9uZ19mb3JfaHMyNTZfYWxnb3JpdGht
    algorithm: PBEWithHMACSHA512AndAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator

# JWT 설정
jwt:
  secret: =a2V5X3ZhbHVlX3RoYXRfaXNfYXRfbGVhc3RfMjU2X2JpdHNfbG9uZ19mb3JfaHMyNTZfYWxnb3JpdGht
  expiration: 3600000

# 모니터링 및 추적 설정
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, tracing
  endpoint:
    prometheus:
      access: read_only
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
      endpoint: ${TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}

# API 문서 설정
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html