global:
  scrape_interval: 15s # 메트릭 수집 간격 (15초 기본값)
  evaluation_interval: 15s # 메트릭 평가 간격

scrape_configs:
  - job_name: 'springboot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['springboot-app:8443']

  - job_name: 'envoy-proxy'
    metrics_path: '/stats/prometheus'
    static_configs:
      - targets: ['envoy-proxy:9901']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgresql'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]
