global:
  scrape_interval: 15s # 메트릭 수집 간격 (15초 기본값)
  evaluation_interval: 15s # 메트릭 평가 간격

scrape_configs:
  - job_name: 'springboot-app' # Spring Boot Application
    metrics_path: '/actuator/prometheus' # Spring Boot Actuator Prometheus 경로
    static_configs:
      - targets: ['springboot-app:8080'] # Spring Boot 컨테이너 및 포트

  - job_name: 'envoy-proxy' # Envoy Proxy
    metrics_path: '/stats/prometheus' # Envoy 프로메테우스 메트릭 지원 경로
    static_configs:
      - targets: ['envoy-proxy:9901'] # Envoy Admin 서비스의 메트릭 EndPoint

  - job_name: 'prometheus' # Prometheus 자체 메트릭 수집
    static_configs:
      - targets: ['localhost:9090'] # Prometheus 서비스